version: 2

project_name: hew

before:
  hooks:
    - go mod tidy
    - go fmt ./...
    - go vet ./...

builds:
  - id: hew
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X github.com/wallanaq/hew/internal/version.version=v{{ .Version }}
      - -X github.com/wallanaq/hew/internal/version.commit={{ .ShortCommit }}
    main: ./cmd/main.go

archives:
  - formats: ['tar.gz']
    name_template: '{{ .ProjectName }}-v{{ .Version }}-{{ .Os }}-{{ .Arch }}'
    format_overrides:
      - goos: windows
        formats: ['zip']

nfpms:
  - id: hew
    package_name: hew
    builds:
      - hew
    vendor: wallanaq
    homepage: https://github.com/wallanaq/hew
    maintainer: wallanaq <wallanaq@users.noreply.github.com>
    description: Sharp tools for developers. Hew through repetitive tasks.
    license: MIT
    formats:
      - deb
      - rpm
    bindir: /usr/bin

checksum:
  name_template: '{{ .ProjectName }}-v{{ .Version }}-checksum.txt'

snapshot:
  version_template: '{{ .Version }}-next'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

release:
  prerelease: auto
  name_template: 'v{{ .Version }}'
