version: 2

project_name: hew

before:
  hooks:
    - go mod tidy
    - go fmt ./...
    - go vet ./...

builds:
  - id: hew
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X github.com/wallanaq/hew/internal/version.version={{ .Version }}
      - -X github.com/wallanaq/hew/internal/version.commit={{ .ShortCommit }}
    main: ./cmd/main.go

archives:
  - formats: ['tar.gz']
    name_template: '{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}'
    format_overrides:
      - goos: windows
        formats: ['zip']

checksum:
  name_template: '{{ .ProjectName }}-{{ .Version }}-checksum.txt'

snapshot:
  version_template: '{{ .Tag }}-{{ .ShortCommit }}-snapshot'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

release:
  prerelease: auto
  name_template: '{{ .Version }}'
